export default [
  "packages/shared",
  "packages/esbuild-wasm-mcp",
  "packages/hackernews-mcp",
  "packages/openclaw-mcp",
  "packages/spike-review",
  "packages/spike-cli",
  "packages/vibe-dev",
  "packages/react-ts-worker",
  "packages/code",
  "packages/transpile",
  "packages/spike-land-backend",
  "packages/spike.land",
  "packages/video",
];
