name = "spike-db"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[durable_objects]
bindings = [
  { name = "SPIKE_DATABASE", class_name = "SpikeDatabase" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SpikeDatabase"]

[vars]
IDENTITY_SECRET = "dev-identity-secret"
