name: Receive Dependency Update

on:
  repository_dispatch:
    types: [dependency-updated]

jobs:
  bump:
    permissions:
      contents: read
    uses: spike-land-ai/.github/.github/workflows/bump-dependency.yml@main
    with:
      package-name: ${{ github.event.client_payload.package }}
      new-version: ${{ github.event.client_payload.version }}
      package-manager: yarn
    secrets: inherit
