name = "status"
main = "../../src/utilities/status/core-logic/index.ts"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "status.spike.land"
custom_domain = true
